package POJO;
// Generated May 31, 2011 10:22:52 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

     private String account;
     private Role role;
	private String pass;
     private String fullName;
     private Date birthday;
     private String sex;
     private Date registerDate;
   	private String address;
     private String phone;
     private String email;
     private String state;
     private Set productorders = new HashSet(0);
	 private Set products = new HashSet(0);
	 private Set notices = new HashSet(0);
	 private Set companys = new HashSet(0);
	 private Set banks = new HashSet(0);
	 private Set deliverCosts = new HashSet(0);
	 private Set shippingcompanys=new HashSet(0);
    


	public User() {
    }

	
    public User(String account, Role role, String pass, String fullName, Date birthday, String sex,Date registerDate, String address, String phone, String email,String state) {
        this.account = account;
        this.role = role;
        this.pass = pass;
        this.fullName = fullName;
        this.birthday = birthday;
        this.sex = sex;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.state = state;
        this.registerDate = registerDate;
    }
    public User(String account, Role role, String pass, String fullName, Date birthday, String sex,Date registerDate, String address, String phone, String email,String state, Set productorders, Set products, Set notices, Set companys, Set banks,Set shippingcompanys) {
       this.account = account;
       this.role = role;
       this.companys = companys;
       this.pass = pass;
       this.fullName = fullName;
       this.birthday = birthday;
       this.sex = sex;
       this.registerDate = registerDate;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.state = state;
       this.productorders = productorders;
	   this.products = products;
	   this.notices = notices;
	   this.banks = banks;
	   this.shippingcompanys=shippingcompanys;
    }
   
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    

    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getRegisterDate() {
		return registerDate;
	}


	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getState() {
		return state;
	}


	public void setState(String state) {
		this.state = state;
	}

    public Set getProductorders() {
        return this.productorders;
    }
    
    public void setProductorders(Set productorders) {
        this.productorders = productorders;
    }
	
	public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }

    public Set getNotices() {
		return notices;
	}


	public void setNotices(Set notices) {
		this.notices = notices;
	}


	public Set getCompanys() {
		return companys;
	}


	public void setCompanys(Set companys) {
		this.companys = companys;
	}
	

	public Set getBanks() {
		return banks;
	}


	public void setBanks(Set banks) {
		this.banks = banks;
	}


	public Set getDeliverCosts() {
		return deliverCosts;
	}


	public void setDeliverCosts(Set deliverCosts) {
		this.deliverCosts = deliverCosts;
	}


	public Set getShippingcompanys() {
		return shippingcompanys;
	}


	public void setShippingcompanys(Set shippingcompanys) {
		this.shippingcompanys = shippingcompanys;
	}


}


